### ISSUE TITLE
Include websites dedicated to saturn game cover arts in the google query

### ISSUE THREAD

**Issue by handsaway** [retrohead/satiator-rings-config#1]
In the current version, the tool to automatically retrieve some searches for the cover art of a game returns lots of pictures of seller ads for the physical game. Hence it is frequent to have 80% of photographs looking like they come from ebay.
Would it be possible to force the search on pages such as [segaretro.org]()? A site that has most [covers](https://segaretro.org/File:Segarally_sat_jp_frontcover.jpg) for all regions?

**Comment by retrohead** [comment]
Invalid issue. You can add your own boxes. Restricting the google search further does not help, it just makes it less useful. segaretro in the example contains full size boxes which come up in the query result, these don't work well in the app.
